version: 4.0.{build}

configuration: Release

image: Visual Studio 2019

branches:
  only:
    - master

before_build:
  - nuget restore

build:
  publish_nuget: true

deploy:
  provider: NuGet
  skip_symbols: true
  artifact: /.*\.nupkg/
  api_key:
    secure: o6YibhkhUt+doruc/1YfXRWj45W9HMO+KRWjxsH8OfwO7OTNfVWwnkXb9h6otVyD
  on:
    branch: master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
