version: 1.0.{build}

configuration: Release

image: Visual Studio 2017

branches:
  only:
    - master

before_build:
  - nuget restore

build:
  publish_nuget: true
  verbosity: detailed

deploy:
  provider: NuGet
  skip_symbols: true
  artifact: /.*\.nupkg/
  api_key:
    secure: Dln/VbbqTt++lS2ICbG45WE49bv1mmS7oWPet9yMH7bYY3/6ne2eD4UArqx6I58j
  on:
    branch: master

nuget:
  project_feed: true
  account_feed: true

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

notifications:
  - provider: Email
    to:
      - rF3rOJnrp78Zda0zX3BkzL5tv2mY9UzvtIU3oAPrk5Q=
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true